test_app/config/routes.rb
Rails.application.routes.draw do
  get 'login', to: 'session#new', as: 'new'
  post 'login', to: 'session#create', as: 'login'
  get 'logout', to: 'session#destroy', as: 'logout'
  resources :data
  root 'session#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

test_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

test_app/app/models/ilance_category.rb
class IlanceCategory < ApplicationRecord
end

test_app/app/models/ilance_project.rb
class IlanceProject < ApplicationRecord
  belongs_to :ilance_user,:class_name => "IlanceUser", :foreign_key => "user_id"
  belongs_to :ilance_category,:class_name => "IlanceCategory", :foreign_key => "cid"
end

test_app/app/models/ilance_user.rb
class IlanceUser < ApplicationRecord
	OPERATIONS = ["Recent", "Project", "Username", "Category"]
	has_many :ilance_projects, foreign_key: 'user_id'
end

test_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user

    rescue_from ::ActionController::RoutingError, with: :error_occurred


    def error_occurred(exception)
      flash[:danger] = 'Kindly Try Again'
      redirect_to data_index_path
    end

    def session_authenticate
      redirect_to root_path unless current_user.present?
    end

    def current_user
      @current_user ||= IlanceUser.find(session[:user_id])
    rescue StandardError
      session.delete(:user_id)
      nil
    end

end

test_app/app/controllers/data_controller.rb
class DataController < ApplicationController
  def index
    respond_to do |format|
      format.html { }
      format.json { render json: DataDatatable.new(view_context) }
    end
  end
end

test_app/app/controllers/session_controller.rb
require 'digest/md5'
class SessionController < ApplicationController
  def new
    if current_user
      redirect_to data_path
    else
      flash[:alert] = nil
      render 'login'
    end
  end

  def create
    user = IlanceUser.find_by_username(params[:session][:username])
    params[:session][:password] = Digest::MD5.hexdigest("#{Digest::MD5.hexdigest(params[:session][:password])}#{user.salt}")
    if user && user.password == params[:session][:password]
      session[:user_id] = user.id
      redirect_to data_path, notice: 'Logged in!'
    else
      flash[:alert] = 'Username or password is invalid'
      render 'login'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'Logged Out !!'
    redirect_to root_url
  end

  private

  def employee_params
    params.require(:session).permit(:username, :password)
  end
end

test_app/app/helpers/application_helper.rb
module ApplicationHelper
end

test_app/app/helpers/data_helper.rb
module DataHelper
end

test_app/app/views/data/_sorting_options.html.haml
.col-sm-2.col-form-label-sm
  .form-group
    %label.text-secondary Sort Options :
.col-sm-3.mb-3
  %select.form-control.task-filter-height#sort-options
    %option{value: "0"} Recent Projects
    %option{value: "1"} Project
    %option{value: "2"} Username
    %option{value: "3"} Category

test_app/app/views/data/index.html.haml
%html
  %body
    = link_to "logout", logout_path if current_user
    = link_to "login", login_path if !current_user
    .content-wrapper
      / Content Header (Page header)
      .content-header
        .container-fluid
          .row.mb-2
            .col-sm-6
              %h1.m-0.text-dark Data

      .content
        .row
          = render 'sorting_options'
          .col-12
            .card
              .card-body.table-responsive
                %table#projects.display{"data-source" => "#{data_url(format: "json")}"}
                  %thead
                    %tr
                      %th Project Title
                      %th Username
                      %th Category

test_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

test_app/app/views/session/login.html.haml
= flash[:notice]
= flash[:alert]
= link_to "Skip Login", data_path
- if(!current_user)
  %h1 LOGIN PLEASE !!
  = form_with scope: :session, url: login_path, local: true do |form|
    .field
      = form.label :username
      = form.text_field :username
    .field
      = form.label :password
      = form.password_field :password
    .actions
      = form.submit "Login"